version: '3'

services:
  telegram-bot-img:
    build:
      context: .
      dockerfile: Dockerfile.img
    container_name: telegram-bot-img
    ports:
      - "8081:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONOPTIMIZE=2
      - PORT=8080
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - URL=${URL}
      - USER_AGENTS_URL=${USER_AGENTS_URL}
      - PING_URL=${PING_URL}
      - TZ=Asia/Phnom_Penh
      - ENABLE_SCREENSHOTS=true
    volumes:
      - ./logs:/app/logs
      - ./GOOGLE_CREDENTIALS_JSON.json:/app/GOOGLE_CREDENTIALS_JSON.json
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3 